# booklist: booklist.c
# 	gcc -o booklist booklist.c -I/usr/include/mysql -L/usr/lib/mysql -lmysqlclient
booklist: booklist.c
	gcc -o booklist booklist.c -I/usr/include/mysql -L/usr/lib/mysql -lmysqlclient